spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect  # 또는 적절한 MySQL 방언
    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true
  profiles:
    include: db

  data:
    redis:
      host: localhost
      port: 6379


logging.level:
  org.springframework.cache: trace # Redis 사용에 대한 로그가 조회되도록 설정
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6


## local 환경
#spring:
#  profiles:
#    default: local
#  datasource:
#    url: jdbc:mysql://localhost:3306/mydb
#    username: root
#    password: password
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true