spring:
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: ${DRIVER_CLASS_NAME}

  data:
    redis:
      host: ${LOCAL_REDIS_HOST}
      port: ${LOCAL_REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: ${DATABASE_PLATFORM}
    properties:
      hibernate:
        format_sql: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


server:
  port:${SERVER_PORT}


cloud:
  aws:
    s3:
      bucket: ${AWS_BUCKET_NAME}
    stack:
      auto: false
    region:
      static: ${AWS_BUCKET_REGION}
    credentials:
      access-key: ${AWS_BUCKET_ACCESSKEY}
      secret-key: ${AWS_BUCKET_SECRETKEY}


logging.level:
  org.springframework.cache: trace # Redis 사용에 대한 로그가 조회되도록 설정
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6






