spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect  # 또는 적절한 MySQL 방언
    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true
  profiles:
    include: db


logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6


